name: validate-csvs
on:
  workflow_dispatch:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
    branches:    
      - 'main'
      - 'test_ci'
    paths:
      - '**.csv'
  push:
    branches:
      - 'main'
jobs:
  validate-csvs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build csv validator
        run: cargo build --manifest-path ./validator/Cargo.toml --release
      - name: Validate hospital price data
        run: ./validator/target/release/validator ./price_transparency/hospitals/machine_readable_links.csv hospital_price_transparency
      - name: Validate insurer price data
        run: ./validator/target/release/validator ./price_transparency/insurers/machine_readable_links.csv insurer_price_transparency